spring.application.name=taskmanager-backend

server.port=${PORT:8080}
server.address=0.0.0.0

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.main.lazy-initialization=true
spring.jpa.open-in-view=false





